version: "3.7"
services:
  app:
    image: nymanjens/quizmaster:latest
    stdin_open: true
    tty: true
    ports: ["9006:9006"]
    volumes:
      - ./conf/quiz:/app/conf/quiz
      - ./conf/application.conf:/app/conf/application.conf
    command: "bin/server"
